name: ci
on:
  pull_request:
    branches:
      - master
  push:
    paths-ignore:
      - "docs/**"
      - ".gitignore"
      - "CHANGELOG.md"
      - "DEVELOPERS.md"
      - "LICENSE"
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      # Source: https://github.com/day8/dockerfile-for-dev-ci-image
      image: day8au/dev-ci:0.0.8
    steps:
      - uses: actions/checkout@v2
        with:
          # All of the Git history is required for day8/lein-git-inject to determine the version string.
          fetch-depth: 0
      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/project.clj') }}-${{ hashFiles('**/deps.cljs') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Sample Project shadow-cljs compiler cache
        uses: actions/cache@v2
        with:
          path: examples/todomvc/.shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-
      - run: lein test
      - name: Install re-frame-10x for Sample Projects
        run: lein install
      - name: Compile Sample Project
        run: |
          pwd
          ls -a
          ls ../..
          lein with-profile dev do clean, shadow compile app
        working-directory: "examples/todomvc"
      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: (failure() || cancelled()) && github.event_name == "push"
        with:
          type: ${{ job.status }}
          job_name: re-frame-10x Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
